import Foundation

/// Pure rendering of a folder's `_index.md` table of contents. No I/O: the
/// caller (App target's `VaultIndexService`) gathers `NoteEntry` values from
/// the vault files + the derived index, then hands them here. Deterministic
/// output is the point — compare-before-write only breaks the reindex loop
/// if two runs over identical inputs render byte-identical text.
public enum IndexFileRenderer {
    /// First line of every generated file — the "do not edit" contract.
    public static let header =
        "<!-- Auto-generated by Notetaker — do not edit; changes are overwritten. -->"

    /// One note's row in a folder's index. All fields are precomputed by the
    /// caller (title/modifiedAt from the derived index; summary/isLocked
    /// from a file read — both are I/O this pure type never performs).
    public struct NoteEntry: Equatable, Sendable {
        /// Vault-relative path, e.g. "Meetings/Bob.md" — the link is built
        /// from its last path component.
        public let noteId: String
        public let title: String
        public let modifiedAt: Date?
        public let openTaskCount: Int
        public let tags: [String]
        public let isLocked: Bool
        /// First non-empty, non-heading, non-task body line (already
        /// truncated to 120 chars); nil when locked or no such line exists.
        public let summary: String?

        public init(
            noteId: String, title: String, modifiedAt: Date?, openTaskCount: Int,
            tags: [String], isLocked: Bool, summary: String?
        ) {
            self.noteId = noteId
            self.title = title
            self.modifiedAt = modifiedAt
            self.openTaskCount = openTaskCount
            self.tags = tags
            self.isLocked = isLocked
            self.summary = summary
        }

        var filename: String {
            noteId.split(separator: "/").last.map(String.init) ?? noteId
        }
    }

    /// Renders one folder's `_index.md`. `folderPath` is "" for the vault
    /// root; `subfolders` and `notes` are the folder's DIRECT children only
    /// (one level — each child folder's own `_index.md` covers the rest).
    public static func render(
        folderPath: String, notes: [NoteEntry], subfolders: [String]
    ) -> String {
        let name = folderPath.isEmpty
            ? "Vault root"
            : (folderPath.split(separator: "/").last.map(String.init) ?? folderPath)

        var lines = [header, "", "# Index — \(name)"]

        let sortedSubfolders = subfolders.sorted { $0.lowercased() < $1.lowercased() }
        if !sortedSubfolders.isEmpty {
            lines.append("")
            for sub in sortedSubfolders {
                lines.append("- 📁 [\(sub)/](\(encoded(sub))/_index.md)")
            }
        }

        let sortedNotes = notes.sorted { $0.filename.lowercased() < $1.filename.lowercased() }
        if !sortedNotes.isEmpty {
            lines.append("")
            for note in sortedNotes {
                lines.append(renderNoteLine(note))
            }
        }

        return lines.joined(separator: "\n") + "\n"
    }

    private static func renderNoteLine(_ note: NoteEntry) -> String {
        guard !note.isLocked else {
            return "- 🔒 \(note.title) — locked note"
        }

        var details: [String] = []
        if let summary = note.summary, !summary.isEmpty {
            details.append(summary)
        }
        if !note.tags.isEmpty {
            details.append(note.tags.sorted().map { "#\($0)" }.joined(separator: " "))
        }
        if note.openTaskCount > 0 {
            details.append("\(note.openTaskCount) open task\(note.openTaskCount == 1 ? "" : "s")")
        }
        if let modifiedAt = note.modifiedAt {
            details.append("\(dayFormatter.string(from: modifiedAt)) modified")
        }

        let link = "[\(note.title)](\(encoded(note.filename)))"
        return details.isEmpty
            ? "- \(link)"
            : "- \(link) — \(details.joined(separator: " · "))"
    }

    /// First non-empty, non-heading, non-task line of a note's body,
    /// truncated to 120 chars; nil when no such line exists. Pure text
    /// scan — the caller supplies the body (post-frontmatter) string.
    public static func extractSummary(fromBody body: String) -> String? {
        for rawLine in body.split(separator: "\n", omittingEmptySubsequences: false) {
            let trimmed = rawLine.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { continue }
            guard !trimmed.hasPrefix("#") else { continue }
            guard !isTaskLine(trimmed) else { continue }
            return trimmed.count > 120 ? String(trimmed.prefix(120)) + "…" : trimmed
        }
        return nil
    }

    private static func isTaskLine(_ trimmed: String) -> Bool {
        trimmed.hasPrefix("- [ ]") || trimmed.hasPrefix("- [x]") || trimmed.hasPrefix("- [X]")
    }

    private static func encoded(_ component: String) -> String {
        component.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? component
    }

    private static let dayFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.dateFormat = "yyyy-MM-dd"
        return formatter
    }()
}
